asyncapi: 2.0.0
info:
  title: User Event API
  version: 1.0.0
description: " User Event API Specification"
swagger: "2.0"
paths: {}
definitions: {}
responses: {}
parameters: {}
securityDefinitions: {}
tags: []
